name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-22.04"
    continue-on-error: ${{ matrix.can-fail }}

    strategy:
      matrix:
        include:
#          - php-version: 8.0
#            composer-flags: ""
#            can-fail: false
#            symfony-require: "6.0.*"
#          - php-version: 8.1
#            composer-flags: ""
#            can-fail: false
#            symfony-require: "6.1.*"
#          - php-version: 8.2
#            composer-flags: ""
#            can-fail: false
#            symfony-require: "6.2.*"
          - php-version: 8.3
            composer-flags: ""
            can-fail: false
            symfony-require: "7.0.*"
#          - php-version: 8.2
#            composer-flags: ""
#            can-fail: true # we don't want to fail the build if we are incompatible with the next (unstable) Symfony version

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Install PHP with XDebug"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.coverage != '' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "xdebug"
          tools: "composer:v2,flex"

      - name: "Install PHP without coverage"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.coverage == '' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "none"
          tools: "composer:v2,flex"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v3"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        env:
          SYMFONY_REQUIRE: "${{ matrix.symfony-require }}"
        run: |
          composer remove friendsofphp/php-cs-fixer --dev --no-update
          composer update --no-interaction --no-progress ${{ matrix.composer-flags }}

      - name: "Run PHPUnit"
        if: "${{ matrix.coverage != '' }}"
        run: |
          XDEBUG_MODE=coverage ./phpunit --coverage-clover=coverage.clover
          wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.clover

      - name: "Run PHPUnit"
        if: "${{ matrix.coverage == '' }}"
        run: "./phpunit"