# GitHub Action for Symfony
name: Testing Symfony
on: [push, pull_request]
jobs:
  symfony:
    name: Symfony ${{ matrix.symfony }} / PHP ${{ matrix.php-versions }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        #windows-latest, macos-latest
        operating-system: [ubuntu-latest]
        php-versions: ['8.2', '8.3']
        symfony: ['5.4', '6.4', '7.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit-bridge
          extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite
          coverage: xdebug
        
      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Composer update on php ${{ matrix.php }} and symfony ${{ matrix.symfony }}
        run: SYMFONY_REQUIRE=${{ matrix.symfony }} composer update --prefer-dist --no-progress

      - name: Install PHPUnit
        run: simple-phpunit install

      - name: Run tests
        run: simple-phpunit --coverage-text

      - name: PHP-CS-Fixer
        uses: docker://ghcr.io/php-cs-fixer/php-cs-fixer:3-php8.3
        with:
          args: check .