name: Split Monorepo

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  split:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: 'htmx-bundle'
            local_path: 'packages/htmx-bundle'
            split_repository: 'mdxpl/htmx-bundle'
          - name: 'htmx-bundle-demo'
            local_path: 'packages/demo'
            split_repository: 'mdxpl/htmx-bundle-demo'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split ${{ matrix.package.name }}
        uses: claudiodekker/splitsh-action@v1
        with:
          local_path: ${{ matrix.package.local_path }}
          split_repository: ${{ matrix.package.split_repository }}
          split_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}

      - name: Push tag to ${{ matrix.package.name }}
        if: startsWith(github.ref, 'refs/tags/')
        uses: claudiodekker/splitsh-action@v1
        with:
          local_path: ${{ matrix.package.local_path }}
          split_repository: ${{ matrix.package.split_repository }}
          split_branch: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_TOKEN }}
